### ISSUE TITLE
Repository should be named "ModernFlyouts-Community.github.io"

### ISSUE THREAD

**Issue by tropicaaal** [ModernFlyouts-Community/ModernFlyouts-Community.github.io#2]
GitHub pages will only detect a "profile" type page if the repository name matches the name of the user or organization. The current URL is located at [https://modernflyouts-community.github.io/ModernFlyouts.github.io/](https://modernflyouts-community.github.io/ModernFlyouts.github.io/), but will be relocated to [https://modernflyouts-community.github.io/](https://modernflyouts-community.github.io/) after the name change.

**Comment by ShankarBUS** [comment]
Ah good catch!

I'll assign @Cyberdroid1 to do that.

**Comment by ShankarBUS** [comment]
Done!
