### ISSUE TITLE
Visuals problems

### ISSUE THREAD

**Issue by FJduFou** [ModernFlyouts-Community/ModernFlyouts-Community.github.io#5]
![image](https://user-images.githubusercontent.com/46401854/103701245-f4c9dc00-4fa5-11eb-8255-c1ba53b72e81.png)
Problem 1

**Comment by tropicaaal** [comment]
Will take a look. Only really looked into browser compatibility with chrome/firefox. As for the favicon, that was on my todo list.

**Comment by FJduFou** [comment]
`<link rel="shortcut icon" type="image/png" href="./rsc/logo.png" />` for favicon
